// <auto-generated />
using BDDNET.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace BDDNET.Migrations
{
    [DbContext(typeof(BiblioContext))]
    [Migration("20240617142110_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.6")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("BDDNET.Models.Auteur", b =>
                {
                    b.Property<int>("IdAuteur")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id_auteur");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdAuteur"));

                    b.Property<string>("NomAuteur")
                        .IsRequired()
                        .HasColumnType("VARCHAR(50)")
                        .HasColumnName("nom_auteur");

                    b.Property<string>("PrenomAuteur")
                        .IsRequired()
                        .HasColumnType("VARCHAR(50)")
                        .HasColumnName("prenom_auteur");

                    b.HasKey("IdAuteur");

                    b.ToTable("Auteurs");
                });

            modelBuilder.Entity("BDDNET.Models.Livre", b =>
                {
                    b.Property<int>("IdLivre")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id_livre");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdLivre"));

                    b.Property<int>("IdAuteur")
                        .HasColumnType("int")
                        .HasColumnName("id_auteur");

                    b.Property<string>("ResumerLivre")
                        .IsRequired()
                        .HasColumnType("VARCHAR(255)")
                        .HasColumnName("resumer_livre");

                    b.Property<string>("TitreLivre")
                        .IsRequired()
                        .HasColumnType("VARCHAR(50)")
                        .HasColumnName("titre_livre");

                    b.HasKey("IdLivre");

                    b.HasIndex("IdAuteur");

                    b.ToTable("Livres");
                });

            modelBuilder.Entity("BDDNET.Models.Livre", b =>
                {
                    b.HasOne("BDDNET.Models.Auteur", "IdAuteurNavigation")
                        .WithMany("Livres")
                        .HasForeignKey("IdAuteur")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("IdAuteurNavigation");
                });

            modelBuilder.Entity("BDDNET.Models.Auteur", b =>
                {
                    b.Navigation("Livres");
                });
#pragma warning restore 612, 618
        }
    }
}
